when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
        requirements:
            _locale: 'en|ru'
        defaults:
            _locale: 'en'
